package com.cursos;

import com.cursos.controller.CursoController;
import com.cursos.model.Curso;

public class Principal extends javax.swing.JFrame {
    
    String modo = "Navegar";
    CursoController CursoController;

    public Principal() {
        CursoController = new CursoController();
        initComponents();
        setLocationRelativeTo(null);
        
        modo = "Navegar";
        ControleVisualizacaoCamposCurso();
        
        carregarTabelaCurso();
    }

    public void carregarTabelaCurso() {
        tbl_Cursos.setModel(CursoController.CarregarTabela());
    }

    public void ControleVisualizacaoCamposCurso() {
        switch (modo) {
            case "Navegar":
                btn_addCurso.setEnabled(true);
                btn_alterarCurso.setEnabled(false);
                btn_CancelarCurso.setEnabled(false);
                btn_excluirCurso.setEnabled(false);
                btn_SalvarCurso.setEnabled(false);
                input_IdCurso.setEnabled(false);
                input_NomeCurso.setEnabled(false);
                break;
            case "Novo":
                btn_addCurso.setEnabled(false);
                btn_alterarCurso.setEnabled(false);
                btn_CancelarCurso.setEnabled(true);
                btn_excluirCurso.setEnabled(false);
                btn_SalvarCurso.setEnabled(true);
                input_IdCurso.setEnabled(true);
                input_NomeCurso.setEnabled(true);
                break;
            case "Editar":
                btn_addCurso.setEnabled(false);
                btn_alterarCurso.setEnabled(false);
                btn_CancelarCurso.setEnabled(true);
                btn_excluirCurso.setEnabled(false);
                btn_SalvarCurso.setEnabled(true);
                input_IdCurso.setEnabled(true);
                input_NomeCurso.setEnabled(true);
                break;
            case "Excluir":
                btn_addCurso.setEnabled(true);
                btn_alterarCurso.setEnabled(false);
                btn_CancelarCurso.setEnabled(false);
                btn_excluirCurso.setEnabled(false);
                btn_SalvarCurso.setEnabled(false);
                input_IdCurso.setEnabled(false);
                input_NomeCurso.setEnabled(false);
                break;
            case "Selecao":
                btn_addCurso.setEnabled(true);
                btn_alterarCurso.setEnabled(true);
                btn_CancelarCurso.setEnabled(false);
                btn_excluirCurso.setEnabled(true);
                btn_SalvarCurso.setEnabled(false);
                input_IdCurso.setEnabled(false);
                input_NomeCurso.setEnabled(false);
                break;
            default:
                System.out.println("Modo Inválido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Cursos = new javax.swing.JTable();
        CadastroCurso = new javax.swing.JPanel();
        label_IdCurso = new javax.swing.JLabel();
        input_IdCurso = new javax.swing.JTextField();
        label_NomeCurso = new javax.swing.JLabel();
        input_NomeCurso = new javax.swing.JTextField();
        btn_SalvarCurso = new javax.swing.JButton();
        btn_CancelarCurso = new javax.swing.JButton();
        btn_addCurso = new javax.swing.JButton();
        btn_alterarCurso = new javax.swing.JButton();
        btn_excluirCurso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_Cursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Cursos);
        if (tbl_Cursos.getColumnModel().getColumnCount() > 0) {
            tbl_Cursos.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_Cursos.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        CadastroCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("NOVO CURSO"));

        label_IdCurso.setText("ID");

        input_IdCurso.setEditable(false);
        input_IdCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_IdCursoActionPerformed(evt);
            }
        });

        label_NomeCurso.setText("NOME");

        input_NomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_NomeCursoActionPerformed(evt);
            }
        });

        btn_SalvarCurso.setText("Salvar");
        btn_SalvarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarCursoActionPerformed(evt);
            }
        });

        btn_CancelarCurso.setText("Cancelar");
        btn_CancelarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroCursoLayout = new javax.swing.GroupLayout(CadastroCurso);
        CadastroCurso.setLayout(CadastroCursoLayout);
        CadastroCursoLayout.setHorizontalGroup(
            CadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroCursoLayout.createSequentialGroup()
                        .addGroup(CadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_IdCurso)
                            .addComponent(label_IdCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_NomeCurso)
                            .addComponent(label_NomeCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroCursoLayout.createSequentialGroup()
                        .addComponent(btn_CancelarCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_SalvarCurso)))
                .addContainerGap())
        );
        CadastroCursoLayout.setVerticalGroup(
            CadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_IdCurso)
                    .addComponent(label_NomeCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_NomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_IdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_SalvarCurso)
                    .addComponent(btn_CancelarCurso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_addCurso.setText("ADICIONAR");
        btn_addCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addCursoActionPerformed(evt);
            }
        });

        btn_alterarCurso.setText("EDITAR");
        btn_alterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarCursoActionPerformed(evt);
            }
        });

        btn_excluirCurso.setText("EXCLUIR");
        btn_excluirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_addCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(btn_alterarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_excluirCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CadastroCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_addCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluirCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CadastroCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cursos", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Alunos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_IdCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_IdCursoActionPerformed

    }//GEN-LAST:event_input_IdCursoActionPerformed

    private void input_NomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_NomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_NomeCursoActionPerformed

    private void btn_CancelarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarCursoActionPerformed
        modo = "Navegar";
        ControleVisualizacaoCamposCurso();
    }//GEN-LAST:event_btn_CancelarCursoActionPerformed

    private void btn_addCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addCursoActionPerformed

        input_IdCurso.setText("0");
        input_NomeCurso.setText("");
        modo = "Novo";
        ControleVisualizacaoCamposCurso();
    }//GEN-LAST:event_btn_addCursoActionPerformed

    private void btn_alterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarCursoActionPerformed
        modo = "Editar";
        ControleVisualizacaoCamposCurso();
    }//GEN-LAST:event_btn_alterarCursoActionPerformed

    private void btn_excluirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirCursoActionPerformed
        int index = tbl_Cursos.getSelectedRow();
                
        if (index >= 0) {
            int id = Integer.parseInt(input_IdCurso.getText());
            CursoController.Excluir(id);
            input_IdCurso.setText("");
            input_NomeCurso.setText("");
        }
        carregarTabelaCurso();
        modo = "Navegar";
        ControleVisualizacaoCamposCurso();
    }//GEN-LAST:event_btn_excluirCursoActionPerformed

    private void btn_SalvarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarCursoActionPerformed
        int id = Integer.parseInt(input_IdCurso.getText());

        if (modo.equals("Novo")) {
            Curso c = new Curso(id, input_NomeCurso.getText());
            CursoController.Incluir(c);
        } else if (modo.equals("Editar")) {
            Curso c = new Curso(id, input_NomeCurso.getText());
            CursoController.Alterar(c);
        }

        carregarTabelaCurso();
        modo = "Navegar";
        ControleVisualizacaoCamposCurso();
        input_IdCurso.setText("");
        input_NomeCurso.setText("");
    }//GEN-LAST:event_btn_SalvarCursoActionPerformed

    private void tbl_CursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CursosMouseClicked
        int index = tbl_Cursos.getSelectedRow();

        if (index >= 0) {
            modo = "Selecao";
            ControleVisualizacaoCamposCurso();

            input_IdCurso.setText(String.valueOf(tbl_Cursos.getModel().getValueAt(index, 0)));
            input_NomeCurso.setText(String.valueOf(tbl_Cursos.getModel().getValueAt(index, 1)));            
        }

    }//GEN-LAST:event_tbl_CursosMouseClicked

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastroCurso;
    private javax.swing.JButton btn_CancelarCurso;
    private javax.swing.JButton btn_SalvarCurso;
    private javax.swing.JButton btn_addCurso;
    private javax.swing.JButton btn_alterarCurso;
    private javax.swing.JButton btn_excluirCurso;
    private javax.swing.JTextField input_IdCurso;
    private javax.swing.JTextField input_NomeCurso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_IdCurso;
    private javax.swing.JLabel label_NomeCurso;
    private javax.swing.JTable tbl_Cursos;
    // End of variables declaration//GEN-END:variables
}
